@extends('layouts.app')
@section('title','Dashboard Analitik') @section('subtitle','Ringkasan performa penjualan RR Jaya Fishing')
@section('content')
<form class="card mb-6 flex flex-wrap items-end gap-3 p-4" method="GET"><label class="field-label">Dari<input class="input mt-1" type="date" name="from" value="{{$from->toDateString()}}"></label><label class="field-label">Sampai<input class="input mt-1" type="date" name="to" value="{{$to->toDateString()}}"></label><button class="btn-primary">Terapkan periode</button><span class="ml-auto self-center text-sm text-slate-500">Diperbarui {{now()->format('d M Y, H:i')}}</span></form>
<div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><x-kpi label="Total Omzet" value="Rp {{number_format($summary['revenue'],0,',','.')}}" icon="Rp" color="teal"/><x-kpi label="Jumlah Transaksi" value="{{number_format($summary['transactions'])}}" icon="↗" color="blue"/><x-kpi label="Produk Terjual" value="{{number_format($summary['items'])}} item" icon="◫" color="amber"/><x-kpi label="Stok Perlu Perhatian" value="{{$lowStocks->count()}} produk" icon="!" color="rose"/></div>
<div class="mt-6 grid gap-6 xl:grid-cols-3"><section class="card p-5 xl:col-span-2"><div class="section-head"><div><h2>Tren Penjualan</h2><p>Omzet harian pada periode terpilih</p></div></div><div class="h-72"><canvas id="trendChart"></canvas></div></section><section class="card p-5"><div class="section-head"><div><h2>Kontribusi Kategori</h2><p>Proporsi omzet penjualan</p></div></div><div class="h-72"><canvas id="categoryChart"></canvas></div></section></div>
<div class="mt-6 grid gap-6 xl:grid-cols-2"><section class="card p-5"><div class="section-head"><div><h2>Produk Terlaris</h2><p>Alat pancing dan pakan ikan</p></div></div><div class="h-64"><canvas id="bestChart"></canvas></div></section><section class="card overflow-hidden"><div class="section-head p-5 pb-3"><div><h2>Peringatan Stok</h2><p>Produk di bawah batas minimum</p></div><span class="badge badge-rose">{{$lowStocks->count()}} perhatian</span></div><div class="divide-y divide-slate-100">@forelse($lowStocks->take(5) as $p)<div class="flex items-center gap-3 px-5 py-3"><div class="product-thumb">{{strtoupper(substr($p->name,0,1))}}</div><div class="min-w-0 flex-1"><div class="truncate text-sm font-semibold">{{$p->name}}</div><div class="text-xs text-slate-500">{{$p->category->name}}</div></div><div class="text-right"><b class="text-rose-600">{{$p->stock}} {{$p->unit}}</b><div class="text-xs text-slate-400">min. {{$p->minimum_stock}}</div></div></div>@empty<div class="empty">Semua stok dalam kondisi aman.</div>@endforelse</div></section></div>
@endsection
@push('scripts')<script>document.addEventListener('DOMContentLoaded',()=>{const money=v=>'Rp '+new Intl.NumberFormat('id-ID').format(v);new Chart(document.getElementById('trendChart'),{type:'line',data:{labels:@json($trend->pluck('transaction_date')->map(fn($d)=>\Carbon\Carbon::parse($d)->format('d M'))),datasets:[{label:'Omzet',data:@json($trend->pluck('total')),borderColor:'#0f766e',backgroundColor:'rgba(15,118,110,.12)',fill:true,tension:.4,pointRadius:3}]},options:{maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:c=>money(c.raw)}}},scales:{y:{ticks:{callback:money},grid:{color:'#eef2f7'}},x:{grid:{display:false}}}}});new Chart(document.getElementById('categoryChart'),{type:'doughnut',data:{labels:@json($categories->pluck('name')),datasets:[{data:@json($categories->pluck('total')),backgroundColor:@json($categories->pluck('color')),borderWidth:0}]},options:{maintainAspectRatio:false,cutout:'68%',plugins:{legend:{position:'bottom',labels:{usePointStyle:true}}}}});const best=@json($best->flatten()->take(7)->values());new Chart(document.getElementById('bestChart'),{type:'bar',data:{labels:best.map(i=>i.name),datasets:[{data:best.map(i=>i.quantity),backgroundColor:best.map(i=>i.type==='alat_pancing'?'#0f766e':'#f59e0b'),borderRadius:7}]},options:{maintainAspectRatio:false,indexAxis:'y',plugins:{legend:{display:false}},scales:{x:{beginAtZero:true,grid:{color:'#eef2f7'}},y:{grid:{display:false}}}}})})</script>@endpush
